/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface MyChild {
    'text': string;
  }
  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface MyParent {
    'disabled': boolean;
    'messageInline': {};
    'tag': string;
  }
}

declare global {


  interface HTMLMyChildElement extends Components.MyChild, HTMLStencilElement {}
  var HTMLMyChildElement: {
    prototype: HTMLMyChildElement;
    new (): HTMLMyChildElement;
  };

  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLMyParentElement extends Components.MyParent, HTMLStencilElement {}
  var HTMLMyParentElement: {
    prototype: HTMLMyParentElement;
    new (): HTMLMyParentElement;
  };
  interface HTMLElementTagNameMap {
    'my-child': HTMLMyChildElement;
    'my-component': HTMLMyComponentElement;
    'my-parent': HTMLMyParentElement;
  }
}

declare namespace LocalJSX {
  interface MyChild {
    'text'?: string;
  }
  interface MyComponent {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }
  interface MyParent {
    'disabled'?: boolean;
    'messageInline'?: {};
    'tag'?: string;
  }

  interface IntrinsicElements {
    'my-child': MyChild;
    'my-component': MyComponent;
    'my-parent': MyParent;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'my-child': LocalJSX.MyChild & JSXBase.HTMLAttributes<HTMLMyChildElement>;
      'my-component': LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
      'my-parent': LocalJSX.MyParent & JSXBase.HTMLAttributes<HTMLMyParentElement>;
    }
  }
}


