/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface JsxConditions {
    'disabled': boolean;
    'tag': string;
  }
  interface MyChild {
    'text': string;
  }
  interface MyParent {
    'disabled': boolean;
    'messageInline': {};
    'tag': string;
  }
  interface MyParentWorkaround {
    'disabled': boolean;
    'messageInline': {};
    'tag': string;
  }
}

declare global {


  interface HTMLJsxConditionsElement extends Components.JsxConditions, HTMLStencilElement {}
  var HTMLJsxConditionsElement: {
    prototype: HTMLJsxConditionsElement;
    new (): HTMLJsxConditionsElement;
  };

  interface HTMLMyChildElement extends Components.MyChild, HTMLStencilElement {}
  var HTMLMyChildElement: {
    prototype: HTMLMyChildElement;
    new (): HTMLMyChildElement;
  };

  interface HTMLMyParentElement extends Components.MyParent, HTMLStencilElement {}
  var HTMLMyParentElement: {
    prototype: HTMLMyParentElement;
    new (): HTMLMyParentElement;
  };

  interface HTMLMyParentWorkaroundElement extends Components.MyParentWorkaround, HTMLStencilElement {}
  var HTMLMyParentWorkaroundElement: {
    prototype: HTMLMyParentWorkaroundElement;
    new (): HTMLMyParentWorkaroundElement;
  };
  interface HTMLElementTagNameMap {
    'jsx-conditions': HTMLJsxConditionsElement;
    'my-child': HTMLMyChildElement;
    'my-parent': HTMLMyParentElement;
    'my-parent-workaround': HTMLMyParentWorkaroundElement;
  }
}

declare namespace LocalJSX {
  interface JsxConditions {
    'disabled'?: boolean;
    'tag'?: string;
  }
  interface MyChild {
    'text'?: string;
  }
  interface MyParent {
    'disabled'?: boolean;
    'messageInline'?: {};
    'tag'?: string;
  }
  interface MyParentWorkaround {
    'disabled'?: boolean;
    'messageInline'?: {};
    'tag'?: string;
  }

  interface IntrinsicElements {
    'jsx-conditions': JsxConditions;
    'my-child': MyChild;
    'my-parent': MyParent;
    'my-parent-workaround': MyParentWorkaround;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'jsx-conditions': LocalJSX.JsxConditions & JSXBase.HTMLAttributes<HTMLJsxConditionsElement>;
      'my-child': LocalJSX.MyChild & JSXBase.HTMLAttributes<HTMLMyChildElement>;
      'my-parent': LocalJSX.MyParent & JSXBase.HTMLAttributes<HTMLMyParentElement>;
      'my-parent-workaround': LocalJSX.MyParentWorkaround & JSXBase.HTMLAttributes<HTMLMyParentWorkaroundElement>;
    }
  }
}


